inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/**/*
Rails:
  Enabled: true
Metrics/MethodLength:
  Max: 25
Metrics/BlockLength:
  Max: 25
  Exclude:
    - spec/**/*